#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ("$SHLVL" -eq 1 && ! -o LOGIN) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

path=(
  $HOME/.local/bin
  $HOME/.ghcup/bin
  /usr/local/{bin,sbin}
  $path
  "/Applications/Visual Studio Code.app/Contents/Resources/app/bin"
)
