# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh


alias use_venv='source ./.venv/bin/activate'
alias lls='ls -lFGh'
alias hi='history'

# Poor man's oh-my-zsh git
alias ga='git add'
alias gp='git pull'
alias gst='git status'
alias gcmsg='git commit -m'

function deproxy {
  unset http_proxy
  unset https_proxy
  unset HTTPS_PROXY
  update_prompt_for_proxy
}
function reproxy {
  export http_proxy=10.116.6.100:10263
  export https_proxy=10.116.6.100:10263
  export HTTPS_PROXY=10.116.6.100:10263
  update_prompt_for_proxy
}